### ISSUE TITLE
Block height basically stopped increasing in alpanet -- Fetch of operations * timed out

### ISSUE THREAD

**Issue by garysdevil** [tezoscommunity/FAQ#12]
Aug 22 05:47:02 - node.validator.bootstrap_pipeline: **Unexpected error (validator)**:
Aug 22 05:47:02 - node.validator.bootstrap_pipeline: Error, dumping error stack:
Aug 22 05:47:02 - node.validator.bootstrap_pipeline:   Fetch of operations BLwqNxJhVZPtX3difB2H9HFwETixXFWYopZeQynkG1vPwZ42aUU:3 timed out
Aug 22 05:47:02 - node.validator.bootstrap_pipeline:   Fetch of operations BLwqNxJhVZPtX3difB2H9HFwETixXFWYopZeQynkG1vPwZ42aUU:2 timed out
Aug 22 05:47:02 - node.validator.bootstrap_pipeline:   Fetch of operations BLwqNxJhVZPtX3difB2H9HFwETixXFWYopZeQynkG1vPwZ42aUU:1 timed out
Aug 22 05:47:02 - node.validator.bootstrap_pipeline:   Fetch of operations BLwqNxJhVZPtX3difB2H9HFwETixXFWYopZeQynkG1vPwZ42aUU:0 timed out
Aug 22 05:47:02 - node.validator.bootstrap_pipeline: 
Aug 22 05:47:02 - main: validator-peer_1162 : Worker crashed [validator-peer_1162]:
Aug 22 05:47:02 - main:                       Fetch of operations BLwqNxJhVZPtX3difB2H9HFwETixXFWYopZeQynkG1vPwZ42aUU:0 timed out
Aug 22 05:47:02 - main:                       Fetch of operations BLwqNxJhVZPtX3difB2H9HFwETixXFWYopZeQynkG1vPwZ42aUU:1 timed out
Aug 22 05:47:02 - main:                       Fetch of operations BLwqNxJhVZPtX3difB2H9HFwETixXFWYopZeQynkG1vPwZ42aUU:2 timed out
Aug 22 05:47:02 - main:                       Fetch of operations BLwqNxJhVZPtX3difB2H9HFwETixXFWYopZeQynkG1vPwZ42aUU:3 timed out(2019-08-22T05:47:02-00:00)
Aug 22 05:51:51 - main: validator-peer_1154 : Worker terminated [validator-peer_1154] (2019-08-22T05:51:51-00:00)
Aug 22 05:52:10 - main: validator-peer_1174 : Worker started for NetXgtSLGNJvN:idsoQXMNqMSJ(2019-08-22T05:52:10-00:00)
Aug 22 05:52:19 - main: validator-peer_1151 : Worker terminated [validator-peer_1151] (2019-08-22T05:52:19-00:00)
Aug 22 05:56:37 - main: prevalidator-NetXgtSLGNJvN-Pt24m4xiPbLD_1 : switching to new head BKzsCkb6wQmF5k3hVeFV5EdgzteR6X63uDy5ZX9Xauk9judW3Jp
Aug 22 05:56:37 - main:                                             Pushed: 2019-08-22T05:46:05-00:00, Treated: 2019-08-22T05:56:34-00:00, Completed: 2019-08-22T05:56:37-00:00(2019-08-22T05:56:37-00:00)
Aug 22 05:56:37 - main: validator-chain_1 : Update current head to BKzsCkb6wQmF5k3hVeFV5EdgzteR6X63uDy5ZX9Xauk9judW3Jp (fitness 00::0000000000f42c77), same branch
Aug 22 05:56:37 - main:                     Pushed: 2019-08-22T05:46:05-00:00, Treated: 2019-08-22T05:46:05-00:00, Completed: 2019-08-22T05:56:37-00:00(2019-08-22T05:56:37-00:00)
Aug 22 05:58:03 - main: validator-block : Block BLwqNxJhVZPtX3difB2H9HFwETixXFWYopZeQynkG1vPwZ42aUU successfully validated
Aug 22 05:58:03 - main:                   Pushed: 2019-08-22T05:58:01-00:00, Treated: 2019-08-22T05:58:01-00:00, Completed: 2019-08-22T05:58:03-00:00(2019-08-22T05:58:03-00:00)
Aug 22 05:58:08 - main: validator-block : Block BLjCXncfEDKYfSUVJSS3XRAawv4byoChni4f7h6UzrvbWjATQgu successfully validated
Aug 22 05:58:08 - main:                   Pushed: 2019-08-22T05:58:07-00:00, Treated: 2019-08-22T05:58:07-00:00, Completed: 2019-08-22T05:58:08-00:00(2019-08-22T05:58:08-00:00)
Aug 22 05:58:14 - main: validator-block : Block BKz8P69oZmgE1HYxYDtV9XJC8TUQ9ZFeLFa2hGHkdvtAKRoCB4r successfully validated
Aug 22 05:58:14 - main:                   Pushed: 2019-08-22T05:58:14-00:00, Treated: 2019-08-22T05:58:14-00:00, Completed: 2019-08-22T05:58:14-00:00(2019-08-22T05:58:14-00:00)
Aug 22 05:58:22 - main: validator-block : Block BMdKiiY3DW6LBAjbiB9CrXGcDi1ggQAvZhuNSkUQZV9UCjgNbTZ successfully validated
Aug 22 05:58:22 - main:                   Pushed: 2019-08-22T05:58:22-00:00, Treated: 2019-08-22T05:58:22-00:00, Completed: 2019-08-22T05:58:22-00:00(2019-08-22T05:58:22-00:00)
Aug 22 05:58:27 - main: validator-block : Block BKkrHaVfR3EzdwyzBiLtsJqZ6mrefZinuCLvkXSzs6jgug4P2Dn successfully validated
Aug 22 05:58:27 - main:                   Pushed: 2019-08-22T05:58:27-00:00, Treated: 2019-08-22T05:58:27-00:00, Completed: 2019-08-22T05:58:27-00:00(2019-08-22T05:58:27-00:00)
Aug 22 05:58:32 - node.validator.bootstrap_pipeline: Unexpected error (validator):
Aug 22 05:58:32 - node.validator.bootstrap_pipeline: Error, dumping error stack:
Aug 22 05:58:32 - node.validator.bootstrap_pipeline:   Fetch of operations BLzwqpuAJA2ZYtAN1EjLbJcC4V1V82JV3gEi1QxvDiNoXfVMVQr:2 timed out
Aug 22 05:58:32 - node.validator.bootstrap_pipeline:   Fetch of operations BLzwqpuAJA2ZYtAN1EjLbJcC4V1V82JV3gEi1QxvDiNoXfVMVQr:0 timed out
Aug 22 05:58:32 - node.validator.bootstrap_pipeline: 
Aug 22 05:58:33 - main: validator-peer_1146 : Worker crashed [validator-peer_1146]:
Aug 22 05:58:33 - main:                       Fetch of operations BLzwqpuAJA2ZYtAN1EjLbJcC4V1V82JV3gEi1QxvDiNoXfVMVQr:0 timed out
Aug 22 05:58:33 - main:                       Fetch of operations BLzwqpuAJA2ZYtAN1EjLbJcC4V1V82JV3gEi1QxvDiNoXfVMVQr:2 timed out(2019-08-22T05:58:33-00:00)
Aug 22 05:59:12 - p2p.maintenance: Too few connections (22)
Aug 22 05:59:28 - p2p.maintenance: Too few connections (22)
Aug 22 06:00:13 - p2p.maintenance: Too few connections (22)
Aug 22 06:01:21 - node.validator.bootstrap_pipeline: Unexpected error (validator):
Aug 22 06:01:21 - node.validator.bootstrap_pipeline: Error, dumping error stack:
Aug 22 06:01:21 - node.validator.bootstrap_pipeline:   Fetch of operations BLzwqpuAJA2ZYtAN1EjLbJcC4V1V82JV3gEi1QxvDiNoXfVMVQr:2 timed out
Aug 22 06:01:21 - node.validator.bootstrap_pipeline:   Fetch of operations BLzwqpuAJA2ZYtAN1EjLbJcC4V1V82JV3gEi1QxvDiNoXfVMVQr:0 timed out
Aug 22 06:01:21 - node.validator.bootstrap_pipeline: 
Aug 22 06:01:21 - main: validator-peer_1169 : Worker crashed [validator-peer_1169]:
Aug 22 06:01:21 - main:                       Fetch of operations BLzwqpuAJA2ZYtAN1EjLbJcC4V1V82JV3gEi1QxvDiNoXfVMVQr:0 timed out
Aug 22 06:01:21 - main:                       Fetch of operations BLzwqpuAJA2ZYtAN1EjLbJcC4V1V82JV3gEi1QxvDiNoXfVMVQr:2 timed out(2019-08-22T06:01:21-00:00)

**Comment by fredcy** [comment]
I suggest that you post this issue on the Tezos StackExchange site: https://tezos.stackexchange.com/

We are not set up to provide general tech support as part of maintaining this FAQ document.
