### ISSUE TITLE
Makefile:24: *** Unexpected opam version (found: 2.1.0, expected: 2.0.*).  Stop.

### ISSUE THREAD

**Issue by benhuang21828** [tezoscommunity/FAQ#16]
Just followed the instruction here https://opentezos.com/deploy-a-node/installation#install-tezos-dependencies-1

ran into this issue 

`Makefile:24: *** Unexpected opam version (found: 2.1.0, expected: 2.0.*).  Stop.`

any suggestions?

**Comment by fredcy** [comment]
I don't know anything about that Open Tezos documentation. Perhaps the version of opam provided by brew is not going to work? I haven't tried building Tezos on MacOS in years. You might be best off asking at tezos.stackexchange.com

**Comment by benhuang21828** [comment]
Posted the question here
https://tezos.stackexchange.com/questions/3744/makefile24-unexpected-opam-version-found-2-1-0-expected-2-0-stop

will circle back if I hear anything about this issue
