### ISSUE TITLE
Update mainnet documentation for proper opam package opam-depext

### ISSUE THREAD

**Issue by utdrmac** [tezoscommunity/FAQ#7]
Documentation continues to refer to package named 'depext' which does not exist in `opam`. The package is named `opam-depext`. 

From https://opam.ocaml.org/packages/depext/

> "This package has been renamed to 'opam-depext' and can safely be removed"

**Comment by fredcy** [comment]
I don't see "depext" or "opam-depext" in the output of `opam list`. Perhaps it's not needed anymore?

**Comment by utdrmac** [comment]
@fredcy `opam list` only shows you what you have installed. `opam list -a` shows all available. If you look at the build-deps scripts, it is still required:

```
$ grep install tezos/scripts/install_build_deps.sh
    opam install --unlock-base ocaml-base-compiler.$ocaml_version
opam list --installed depext || opam install depext
```

**Comment by fredcy** [comment]
I just tried a fresh `make build-deps` (on Ubuntu 16 -- the most convenient test node at hand) and I see this in the output:

```
# Packages matching: installed & name-match(depext)
# No matches found
```

So it appears to me that although install_build_deps.sh tries to install depext, it fails and yet the build-deps step works. I don't know what to make of that.

**Comment by utdrmac** [comment]
Agreed on the fact that everything works even though it is missing. I installed the correct package manually anyways. I posted a PR on gitlab to fix this so maybe a dev will comment there.

**Comment by fredcy** [comment]
Is this still an issue?  I just built from scratch per the document and I did not see anything about depext. Should I remove mention of depext from the document?

**Comment by utdrmac** [comment]
Check the correct name:
```
$ opam list | grep depext
opam-depext             1.1.3        Query and install external dependencies of OPAM packages

$ grep -Iir opam-depext *
docs/releases/may-2019.rst:    - ``e860a7bb1``: ``build-deps: really install and use opam-depext``
...
scripts/update_opam_repo.sh:     --resolve $packages,ocaml,ocaml-base-compiler,odoc,opam-depext,js_of_ocaml-ppx,reactiveData,opam-ed
scripts/install_build_deps.sh:opam install --yes opam-depext
```

**Comment by utdrmac** [comment]
You can probably remove all the comments regarding this package as it's installed automatically now and seems to be fixed/handled by the various build scripts.

**Comment by fredcy** [comment]
Thanks for the help with this, @utdrmac
