### ISSUE TITLE
opam install script 2.0.1

### ISSUE THREAD

**Issue by utdrmac** [tezoscommunity/FAQ#9]
"Opam installation method 1" now installs 2.0.1 by default. This causes the following issue when compiling:

```
$ make build-deps
Makefile:11: *** Unexpected opam version (found: 2.0.1, expected: 2.0.0).  Stop.
```

**Comment by utdrmac** [comment]
Additionally, 2.0.0-rc4 is outdated. There is a proper 2.0.0

**Comment by fredcy** [comment]
Do you have a recommended way to install version 2.0.0?

**Comment by utdrmac** [comment]
@fredcy I used "install method 2" and just changed the URL: ` wget https://github.com/ocaml/opam/releases/download/2.0.0/opam-2.0.0-x86_64-linux`

**Comment by utdrmac** [comment]
I also opened a bug with Tezos team on gitlab asking them to support 2.0.1

**Comment by fredcy** [comment]
Thanks for reporting this issue. I've updated the doc.

**Comment by utdrmac** [comment]
@fredcy This can be reverted. You can put 'Opam installation method 1' back in the docs. The tezos devs made newer opam versions compatible.

**Comment by fredcy** [comment]
OK, I added it back. Thanks.

**Comment by h0v1g** [comment]
This appears to have broken once again with 2.0.3 as the default for sh <(curl -sL https://raw.githubusercontent.com/ocaml/opam/master/shell/install.sh)
